/** English 🇺🇸🇬🇧 — local content for the English-speaking world (USA, UK, Canada, Australia) */
import type { LangContent } from "./types";

export const en: LangContent = {
  decks: {
  animals: {
    cards: [
      "Lion", "Elephant", "Giraffe", "Monkey", "Dog", "Cat", "Penguin", "Dolphin", "Shark", "Octopus",
      "Kangaroo", "Koala", "Zebra", "Hippo", "Rhino", "Tiger", "Bear", "Wolf", "Fox", "Rabbit",
      "Turtle", "Snake", "Crocodile", "Spider", "Bee", "Butterfly", "Owl", "Eagle", "Parrot", "Peacock",
      "Horse", "Donkey", "Cow", "Sheep", "Goat", "Rooster", "Duck", "Goose", "Mouse", "Hamster",
      "Squirrel", "Raccoon", "Moose", "Hedgehog",
    ],
  },
  celebs: {
    cards: [
      "Taylor Swift", "Beyoncé", "Ed Sheeran", "Adele", "Harry Styles", "Dua Lipa", "Elton John", "Ariana Grande", "Billie Eilish", "Drake",
      "Tom Cruise", "Dwayne 'The Rock' Johnson", "Leonardo DiCaprio", "Emma Watson", "Daniel Radcliffe", "Zendaya", "Ryan Reynolds", "Will Smith", "Tom Holland", "Jennifer Lawrence",
      "Oprah Winfrey", "Gordon Ramsay", "David Attenborough", "MrBeast", "Kim Kardashian", "Elon Musk", "Bill Gates", "Steve Jobs", "Walt Disney", "Albert Einstein",
      "Abraham Lincoln", "Winston Churchill", "Queen Elizabeth II", "King Charles", "Prince William", "David Beckham", "Harry Kane", "Lionel Messi", "LeBron James", "Michael Jordan",
      "Serena Williams", "Simone Biles", "Tom Brady", "Usain Bolt",
    ],
  },
  food: {
    cards: [
      "Cheeseburger", "Fish and Chips", "Mac and Cheese", "Sunday Roast", "Tacos", "Sushi", "Pizza", "Hot Dog", "Fried Chicken", "Pancakes",
      "Apple Pie", "Full English Breakfast", "Shepherd's Pie", "Cornish Pasty", "Scones", "Buffalo Wings", "BBQ Ribs", "Grilled Cheese", "PB&J Sandwich", "Nachos",
      "Oreos", "Pop-Tarts", "Cadbury Creme Egg", "Jaffa Cakes", "Beans on Toast", "Chicken Tikka Masala", "Doughnuts", "Cheesecake", "Brownies", "Ice Cream",
      "Strawberries", "Watermelon", "Banana", "Avocado Toast", "Pumpkin Pie", "Cheetos", "Yorkshire Pudding", "Caesar Salad",
    ],
  },
  cartoons: {
    cards: [
      "SpongeBob", "Patrick Star", "Peppa Pig", "Bluey", "Homer Simpson", "Bart Simpson", "Elsa (Frozen)", "Olaf", "Shrek", "Donkey (Shrek)",
      "Pikachu", "Mario", "Luigi", "Sonic the Hedgehog", "Mickey Mouse", "Bugs Bunny", "Scooby-Doo", "Buzz Lightyear", "Woody (Toy Story)", "Simba",
      "Moana", "Winnie the Pooh", "Minions", "Gru", "Tom (Tom and Jerry)", "Jerry", "Batman", "Spider-Man", "Superman", "Paddington Bear",
      "Wallace and Gromit", "Garfield", "Lightning McQueen", "Stitch", "Bob the Builder", "Dora the Explorer",
    ],
  },
  },
  impostorPairs: [
  ["Pizza", "Burger"], ["Cat", "Dog"], ["Beach", "Pool"], ["Coffee", "Tea"], ["Plane", "Train"],
  ["Wedding", "Prom"], ["Football", "Basketball"], ["Guitar", "Piano"], ["Sun", "Moon"], ["Netflix", "YouTube"],
  ["Christmas", "Halloween"], ["New York", "London"], ["Thanksgiving", "Easter"], ["Uber", "Taxi"], ["Target", "Walmart"],
  ["Tube", "Bus"], ["Ice cream", "Popsicle"], ["Shower", "Bath"], ["Doctor", "Nurse"], ["School", "Summer camp"],
  ["Mom", "Grandma"], ["TV", "Cinema"], ["Couch", "Bed"], ["Winter", "Fall"], ["Wine", "Beer"],
  ["Cake", "Cookies"], ["Desert", "Forest"], ["Bike", "Scooter"], ["Sushi", "Tacos"], ["Cucumber", "Zucchini"],
  ["Sneakers", "Flip-flops"], ["Glasses", "Contact lenses"], ["Book", "Newspaper"], ["Restaurant", "Coffee shop"], ["Rain", "Snow"],
  ["Apple", "Pear"], ["Chocolate", "Chips"], ["Traffic light", "Stop sign"], ["Park", "Playground"], ["Road trip", "Cruise"],
  ["Teacher", "Professor"], ["Baby", "Puppy"], ["Milk", "Chocolate milk"], ["Instagram", "TikTok"], ["Elevator", "Stairs"],
  ["Pillow", "Blanket"], ["BBQ", "Picnic"], ["Singer", "Actor"], ["Birthday cake", "Donut"], ["Running", "Walking"],
  ["Gym", "Yoga"], ["Banana", "Mango"], ["Ketchup", "Mustard"], ["Police officer", "Security guard"], ["Kindergarten", "Daycare"],
  ["Rose", "Sunflower"], ["Disney World", "Universal Studios"], ["Pasta", "Rice"], ["Fridge", "Air conditioner"], ["Wallet", "Purse"],
  ["Watch", "Bracelet"], ["Washing machine", "Dishwasher"], ["Starbucks", "Dunkin'"], ["McDonald's", "Burger King"], ["Harry Potter", "Lord of the Rings"],
  ["Super Bowl", "World Cup"], ["Amazon", "eBay"], ["Hot dog", "Corn dog"], ["Fish and chips", "Chicken nuggets"], ["Pancakes", "Waffles"],
  ["Costco", "IKEA"], ["Zoo", "Aquarium"],
  ],
  undercoverPairs: [
  /* ---------- d:2 — normal ---------- */
  { a: "Pizza", b: "Hot dog", d: 2 },
  { a: "Cat", b: "Hamster", d: 2 },
  { a: "Sea", b: "Lake", d: 2 },
  { a: "Coffee", b: "Hot chocolate", d: 2 },
  { a: "Plane", b: "Helicopter", d: 2 },
  { a: "Wedding", b: "Graduation", d: 2 },
  { a: "Football", b: "Tennis", d: 2 },
  { a: "Guitar", b: "Drums", d: 2 },
  { a: "Sun", b: "Stars", d: 2 },
  { a: "Ice cream", b: "Cupcake", d: 2 },
  { a: "School", b: "Office", d: 2 },
  { a: "Movie theater", b: "Concert", d: 2 },
  { a: "Couch", b: "Hammock", d: 2 },
  { a: "Winter", b: "Summer", d: 2 },
  { a: "Wine", b: "Lemonade", d: 2 },
  { a: "Cake", b: "Pie", d: 2 },
  { a: "Desert", b: "Jungle", d: 2 },
  { a: "Bike", b: "Skateboard", d: 2 },
  { a: "Sushi", b: "Pasta", d: 2 },
  { a: "Sneakers", b: "Boots", d: 2 },
  { a: "Book", b: "Magazine", d: 2 },
  { a: "Restaurant", b: "Food truck", d: 2 },
  { a: "Christmas", b: "Easter", d: 2 },
  { a: "Rain", b: "Wind", d: 2 },
  { a: "Apple", b: "Watermelon", d: 2 },
  { a: "Taxi", b: "Bus", d: 2 },
  { a: "Beach", b: "Park", d: 2 },
  { a: "Singer", b: "Dancer", d: 2 },
  { a: "Running", b: "Swimming", d: 2 },
  { a: "Gym", b: "Spa", d: 2 },
  { a: "Banana", b: "Grapes", d: 2 },
  { a: "Police officer", b: "Firefighter", d: 2 },
  { a: "Kindergarten", b: "Summer camp", d: 2 },
  { a: "Rose", b: "Cactus", d: 2 },
  { a: "Pasta", b: "Soup", d: 2 },
  { a: "Fridge", b: "Oven", d: 2 },
  { a: "Wallet", b: "Suitcase", d: 2 },
  { a: "Umbrella", b: "Hat", d: 2 },
  { a: "Lion", b: "Elephant", d: 2 },
  { a: "Shark", b: "Dolphin", d: 2 },
  { a: "Parrot", b: "Pigeon", d: 2 },
  { a: "Bee", b: "Ant", d: 2 },
  { a: "Motorcycle", b: "Tractor", d: 2 },
  { a: "Washing machine", b: "Vacuum cleaner", d: 2 },
  { a: "Pillow", b: "Mattress", d: 2 },
  { a: "BBQ", b: "Campfire", d: 2 },
  { a: "Circus", b: "Theme park", d: 2 },
  { a: "Museum", b: "Library", d: 2 },
  { a: "Hospital", b: "Hair salon", d: 2 },
  { a: "Supermarket", b: "Farmers market", d: 2 },
  { a: "Toaster", b: "Microwave", d: 2 },
  { a: "Popcorn", b: "Pretzel", d: 2 },
  { a: "Chewing gum", b: "Lollipop", d: 2 },
  { a: "Coca-Cola", b: "Orange juice", d: 2 },
  { a: "Milk", b: "Smoothie", d: 2 },
  { a: "Egg", b: "Cheese", d: 2 },
  { a: "Salad", b: "Sandwich", d: 2 },
  { a: "Fried chicken", b: "Meatballs", d: 2 },
  { a: "Bread", b: "Bagel", d: 2 },
  { a: "Honey", b: "Jam", d: 2 },
  { a: "Thunder", b: "Lightning", d: 2 },
  { a: "Mountain", b: "Volcano", d: 2 },
  { a: "River", b: "Waterfall", d: 2 },
  { a: "Castle", b: "Skyscraper", d: 2 },
  { a: "Tent", b: "Cabin", d: 2 },
  { a: "Dentist", b: "Vet", d: 2 },
  { a: "Pilot", b: "Astronaut", d: 2 },
  { a: "Chef", b: "Waiter", d: 2 },
  { a: "Farmer", b: "Fisherman", d: 2 },
  { a: "Piano", b: "Violin", d: 2 },
  { a: "Soccer", b: "Golf", d: 2 },
  { a: "Baseball", b: "Hockey", d: 2 },
  { a: "Snowman", b: "Sandcastle", d: 2 },
  { a: "Halloween", b: "Thanksgiving", d: 2 },
  { a: "Pumpkin", b: "Corn", d: 2 },
  { a: "Turkey", b: "Chicken", d: 2 },
  { a: "Cheeseburger", b: "Taco", d: 2 },
  { a: "Pancake", b: "Toast", d: 2 },
  { a: "Donut", b: "Croissant", d: 2 },
  { a: "Chocolate", b: "Candy cane", d: 2 },
  { a: "New York", b: "Los Angeles", d: 2 },
  { a: "London", b: "Paris", d: 2 },
  { a: "Disneyland", b: "Zoo", d: 2 },
  { a: "Roller coaster", b: "Ferris wheel", d: 2 },
  { a: "Netflix", b: "Spotify", d: 2 },
  { a: "iPhone", b: "Laptop", d: 2 },
  { a: "Video game", b: "Board game", d: 2 },
  { a: "Minecraft", b: "Fortnite", d: 2 },
  { a: "Lego", b: "Jigsaw puzzle", d: 2 },
  { a: "Barbie", b: "Teddy bear", d: 2 },
  { a: "Superman", b: "Harry Potter", d: 2 },
  { a: "Homer Simpson", b: "SpongeBob", d: 2 },
  { a: "Rocket", b: "Submarine", d: 2 },
  { a: "Pirate", b: "Cowboy", d: 2 },
  { a: "Ghost", b: "Vampire", d: 2 },
  { a: "Robot", b: "Alien", d: 2 },
  { a: "Dragon", b: "Unicorn", d: 2 },
  { a: "Detective", b: "Spy", d: 2 },
  { a: "King", b: "Wizard", d: 2 },
  { a: "Birthday party", b: "Sleepover", d: 2 },
  /* ---------- d:1 — hard ---------- */
  { a: "Strawberry", b: "Cherry", d: 1 },
  { a: "Noon", b: "Afternoon", d: 1 },
  { a: "Dentist", b: "Optician", d: 1 },
  { a: "Earth", b: "Mars", d: 1 },
  { a: "Ant", b: "Cockroach", d: 1 },
  { a: "Latte", b: "Cappuccino", d: 1 },
  { a: "Marvel", b: "DC", d: 1 },
  { a: "iPhone", b: "Samsung", d: 1 },
  { a: "Lemon", b: "Lime", d: 1 },
  { a: "Ketchup", b: "Mayo", d: 1 },
  { a: "Bus", b: "Tram", d: 1 },
  { a: "Muffin", b: "Cupcake", d: 1 },
  { a: "Crocodile", b: "Alligator", d: 1 },
  { a: "Butter", b: "Margarine", d: 1 },
  { a: "Rain", b: "Drizzle", d: 1 },
  { a: "Jam", b: "Jelly", d: 1 },
  { a: "Sofa", b: "Armchair", d: 1 },
  { a: "Pillow", b: "Cushion", d: 1 },
  { a: "Cookie", b: "Cracker", d: 1 },
  { a: "Lake", b: "Pond", d: 1 },
  { a: "Hill", b: "Mountain", d: 1 },
  { a: "Road", b: "Street", d: 1 },
  { a: "Jog", b: "Sprint", d: 1 },
  { a: "Frog", b: "Toad", d: 1 },
  { a: "Turtle", b: "Tortoise", d: 1 },
  { a: "Moth", b: "Butterfly", d: 1 },
  { a: "Seal", b: "Sea lion", d: 1 },
  { a: "Wasp", b: "Hornet", d: 1 },
  { a: "Leopard", b: "Cheetah", d: 1 },
  { a: "Rabbit", b: "Hare", d: 1 },
  { a: "Mouse", b: "Rat", d: 1 },
  { a: "Crow", b: "Raven", d: 1 },
  { a: "Hawk", b: "Eagle", d: 1 },
  { a: "Hoodie", b: "Sweater", d: 1 },
  { a: "Jeans", b: "Leggings", d: 1 },
  { a: "Cap", b: "Beanie", d: 1 },
  { a: "Spoon", b: "Teaspoon", d: 1 },
  { a: "Plate", b: "Bowl", d: 1 },
  { a: "Cup", b: "Mug", d: 1 },
  { a: "Coke", b: "Pepsi", d: 1 },
  { a: "Sprite", b: "7UP", d: 1 },
  { a: "Nike", b: "Adidas", d: 1 },
  { a: "Xbox", b: "PlayStation", d: 1 },
  { a: "Instagram", b: "Snapchat", d: 1 },
  { a: "Google", b: "Bing", d: 1 },
  { a: "Milk", b: "Cream", d: 1 },
  { a: "Doctor", b: "Surgeon", d: 1 },
  { a: "Nurse", b: "Paramedic", d: 1 },
  { a: "Lawyer", b: "Judge", d: 1 },
  { a: "Teacher", b: "Tutor", d: 1 },
  { a: "Actor", b: "Comedian", d: 1 },
  { a: "Wednesday", b: "Thursday", d: 1 },
  { a: "March", b: "April", d: 1 },
  { a: "Morning", b: "Dawn", d: 1 },
  { a: "Minute", b: "Second", d: 1 },
  { a: "Kitchen", b: "Pantry", d: 1 },
  { a: "Hotel", b: "Motel", d: 1 },
  { a: "Cabin", b: "Cottage", d: 1 },
  { a: "Bakery", b: "Cafe", d: 1 },
  { a: "Violin", b: "Cello", d: 1 },
  { a: "Trumpet", b: "Trombone", d: 1 },
  { a: "Chess", b: "Checkers", d: 1 },
  { a: "Soccer", b: "Rugby", d: 1 },
  { a: "Baseball", b: "Cricket", d: 1 },
  { a: "Skiing", b: "Snowboarding", d: 1 },
  { a: "Kayak", b: "Canoe", d: 1 },
  { a: "Jupiter", b: "Saturn", d: 1 },
  { a: "Meteor", b: "Comet", d: 1 },
  { a: "Fog", b: "Mist", d: 1 },
  { a: "Hurricane", b: "Tornado", d: 1 },
  { a: "Penguin", b: "Puffin", d: 1 },
  { a: "Elevator", b: "Escalator", d: 1 },
  ],
  trivia: [
  /* local — USA & UK */
  { q: "How many stripes are on the American flag?", options: ["10", "13", "50", "7"], correct: 1, cat: "israel" },
  { q: "What is the nickname of the famous bell in London's clock tower?", options: ["Big Tom", "Great Paul", "Old Bill", "Big Ben"], correct: 3, cat: "israel" },
  { q: "Which US city is nicknamed 'The Big Apple'?", options: ["Chicago", "Los Angeles", "New York", "Boston"], correct: 2, cat: "israel" },
  { q: "What do Brits call French fries?", options: ["Crisps", "Chips", "Wedges", "Fritters"], correct: 1, cat: "israel" },
  { q: "What is the currency of the United Kingdom?", options: ["Pound", "Euro", "Dollar", "Franc"], correct: 0, cat: "israel" },
  { q: "Which country gave the Statue of Liberty to the USA?", options: ["Spain", "Italy", "Britain", "France"], correct: 3, cat: "israel" },
  { q: "What bird is traditionally eaten at Thanksgiving?", options: ["Duck", "Goose", "Turkey", "Chicken"], correct: 2, cat: "israel" },
  { q: "Which US state is the Grand Canyon in?", options: ["Arizona", "Nevada", "Utah", "Colorado"], correct: 0, cat: "israel" },
  { q: "What is the capital of Scotland?", options: ["Glasgow", "Aberdeen", "Dundee", "Edinburgh"], correct: 3, cat: "israel" },
  { q: "Which city has the Golden Gate Bridge?", options: ["Seattle", "San Francisco", "Los Angeles", "San Diego"], correct: 1, cat: "israel" },
  { q: "In the UK, what is a 'lorry'?", options: ["A truck", "A bus", "A train", "A tractor"], correct: 0, cat: "israel" },
  { q: "What sport is played at Wimbledon?", options: ["Golf", "Cricket", "Tennis", "Rugby"], correct: 2, cat: "israel" },
  /* world */
  { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Perth", "Canberra"], correct: 3, cat: "world" },
  { q: "Which country has more pyramids than Egypt?", options: ["Sudan", "Mexico", "Peru", "Iraq"], correct: 0, cat: "world" },
  { q: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "Malta", "San Marino"], correct: 1, cat: "world" },
  { q: "Which country has the most time zones?", options: ["Russia", "USA", "China", "France"], correct: 3, cat: "world" },
  { q: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2, cat: "world" },
  { q: "Which country has the most islands?", options: ["Sweden", "Indonesia", "Philippines", "Japan"], correct: 0, cat: "world" },
  { q: "Which country is in both Europe and Asia?", options: ["Greece", "Turkey", "Egypt", "Spain"], correct: 1, cat: "world" },
  { q: "How many rings are on the Olympic flag?", options: ["4", "6", "5", "7"], correct: 2, cat: "world" },
  { q: "Which is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3, cat: "world" },
  { q: "Which continent has no countries at all?", options: ["Antarctica", "Australia", "Africa", "South America"], correct: 0, cat: "world" },
  /* science */
  { q: "How many hearts does an octopus have?", options: ["1", "2", "3", "8"], correct: 2, cat: "science" },
  { q: "Which planet spins on its side?", options: ["Neptune", "Uranus", "Venus", "Saturn"], correct: 1, cat: "science" },
  { q: "What is the largest animal that has ever lived?", options: ["Elephant", "T. rex", "Giant squid", "Blue whale"], correct: 3, cat: "science" },
  { q: "Which metal is liquid at room temperature?", options: ["Mercury", "Iron", "Tin", "Silver"], correct: 0, cat: "science" },
  { q: "How long does sunlight take to reach Earth?", options: ["8 seconds", "8 minutes", "8 hours", "8 days"], correct: 1, cat: "science" },
  { q: "What is the largest organ of the human body?", options: ["Liver", "Brain", "Skin", "Lungs"], correct: 2, cat: "science" },
  { q: "How many bones does an adult human have?", options: ["106", "156", "306", "206"], correct: 3, cat: "science" },
  { q: "What is the chemical symbol for gold?", options: ["Au", "Ag", "Go", "Gd"], correct: 0, cat: "science" },
  { q: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Horse", "Greyhound"], correct: 1, cat: "science" },
  { q: "What is the hardest natural substance on Earth?", options: ["Steel", "Granite", "Quartz", "Diamond"], correct: 3, cat: "science" },
  { q: "Which gas do plants absorb from the air?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], correct: 2, cat: "science" },
  { q: "What is the closest star to Earth?", options: ["The Sun", "Sirius", "The North Star", "Alpha Centauri"], correct: 0, cat: "science" },
  ],
};
