/** Español 🌎 — contenido local para el mundo hispano (España + Latinoamérica) */
import type { LangContent } from "./types";

export const es: LangContent = {
  decks: {
  animals: {
    cards: [
      "León", "Elefante", "Jirafa", "Mono", "Perro", "Gato", "Pingüino", "Delfín", "Tiburón", "Pulpo",
      "Canguro", "Koala", "Cebra", "Hipopótamo", "Rinoceronte", "Tigre", "Oso", "Lobo", "Zorro", "Conejo",
      "Tortuga", "Serpiente", "Cocodrilo", "Araña", "Abeja", "Mariposa", "Búho", "Águila", "Loro", "Pavo real",
      "Caballo", "Burro", "Vaca", "Oveja", "Cabra", "Gallo", "Pato", "Ratón", "Llama", "Cóndor",
      "Jaguar", "Flamenco",
    ],
  },
  celebs: {
    cards: [
      "Shakira", "Bad Bunny", "Rosalía", "Lionel Messi", "Cristiano Ronaldo", "Frida Kahlo", "Salma Hayek", "Antonio Banderas", "Penélope Cruz", "Sofía Vergara",
      "Gabriel García Márquez", "Pablo Picasso", "Diego Maradona", "Rafael Nadal", "Karol G", "J Balvin", "Luis Miguel", "Enrique Iglesias", "Ricky Martin", "Jennifer Lopez",
      "Chespirito", "Eugenio Derbez", "Pedro Pascal", "Maluma", "Daddy Yankee", "Taylor Swift", "Beyoncé", "Albert Einstein", "Miguel de Cervantes", "Simón Bolívar",
      "Celia Cruz", "Vicente Fernández", "Michael Jordan", "Peso Pluma", "Luisito Comunica", "Ibai Llanos", "Bizarrap", "Feid", "Thalía",
    ],
  },
  food: {
    cards: [
      "Paella", "Tacos", "Empanadas", "Arepas", "Ceviche", "Churros", "Tortilla española", "Asado", "Dulce de leche", "Guacamole",
      "Tamales", "Pozole", "Gazpacho", "Jamón serrano", "Croquetas", "Alfajores", "Pupusas", "Flan", "Pastel tres leches", "Nachos",
      "Burrito", "Pizza", "Hamburguesa", "Sushi", "Pasta", "Helado", "Sandía", "Mango", "Plátano", "Aguacate",
      "Papas fritas", "Chilaquiles", "Mate", "Horchata", "Chocolate", "Elote", "Tequeños",
    ],
  },
  cartoons: {
    cards: [
      "Bob Esponja", "Patricio Estrella", "Peppa Pig", "El Chavo animado", "Pocoyó", "Homero Simpson", "Bart Simpson", "Elsa (Frozen)", "Shrek", "Pikachu",
      "Mario Bros", "Goku", "Mickey Mouse", "Pato Donald", "Bugs Bunny", "Scooby-Doo", "Woody (Toy Story)", "Buzz Lightyear", "Nemo", "Minion",
      "Spider-Man", "Batman", "Superman", "Hulk", "Simba", "Moana", "Winnie Pooh", "Tom y Jerry", "Dora la Exploradora", "Mafalda",
      "Condorito", "Naruto", "Pedro Picapiedra", "Miguel (Coco)", "Bluey", "Stitch", "Sonic",
    ],
  },
  },
  impostorPairs: [
  ["pizza", "hamburguesa"], ["gato", "perro"], ["playa", "piscina"], ["café", "té"], ["avión", "tren"],
  ["boda", "quinceañera"], ["fútbol", "básquet"], ["Navidad", "Reyes Magos"], ["Madrid", "Barcelona"], ["taco", "burrito"],
  ["guitarra", "piano"], ["sol", "luna"], ["helado", "paleta"], ["ducha", "bañera"], ["médico", "enfermera"],
  ["escuela", "universidad"], ["mamá", "abuela"], ["televisión", "cine"], ["sofá", "cama"], ["invierno", "otoño"],
  ["vino", "cerveza"], ["pastel", "galletas"], ["desierto", "selva"], ["bicicleta", "patineta"], ["sushi", "paella"],
  ["pepino", "zanahoria"], ["zapatos", "chanclas"], ["lentes", "lupa"], ["libro", "periódico"], ["restaurante", "cafetería"],
  ["lluvia", "nieve"], ["manzana", "pera"], ["chocolate", "caramelo"], ["taxi", "autobús"], ["semáforo", "señal de tránsito"],
  ["parque", "plaza"], ["profesor", "entrenador"], ["bebé", "cachorro"], ["leche", "jugo"], ["Facebook", "Instagram"],
  ["sábado", "domingo"], ["ascensor", "escaleras"], ["almohada", "manta"], ["asado", "picnic"], ["cantante", "actor"],
  ["cumpleaños", "Año Nuevo"], ["correr", "caminar"], ["gimnasio", "yoga"], ["plátano", "mango"], ["guacamole", "salsa"],
  ["policía", "bombero"], ["campamento", "excursión"], ["rosa", "girasol"], ["Machu Picchu", "Chichén Itzá"], ["pasta", "arroz"],
  ["refrigerador", "aire acondicionado"], ["cartera", "mochila"], ["reloj", "pulsera"], ["lavadora", "lavavajillas"], ["empanada", "tamal"],
  ["salsa", "reggaetón"], ["Messi", "Cristiano"], ["mate", "chocolate caliente"], ["churros", "donas"], ["piñata", "globos"],
  ],
  undercoverPairs: [
  /* ---------- d:2 — normal ---------- */
  { a: "pizza", b: "hamburguesa", d: 2 },
  { a: "gato", b: "perro", d: 2 },
  { a: "mar", b: "piscina", d: 2 },
  { a: "café", b: "té", d: 2 },
  { a: "avión", b: "tren", d: 2 },
  { a: "boda", b: "quinceañera", d: 2 },
  { a: "taco", b: "empanada", d: 2 },
  { a: "fútbol", b: "básquet", d: 2 },
  { a: "guitarra", b: "piano", d: 2 },
  { a: "sol", b: "luna", d: 2 },
  { a: "helado", b: "chocolate", d: 2 },
  { a: "escuela", b: "universidad", d: 2 },
  { a: "televisión", b: "cine", d: 2 },
  { a: "sofá", b: "cama", d: 2 },
  { a: "invierno", b: "verano", d: 2 },
  { a: "vino", b: "cerveza", d: 2 },
  { a: "pastel", b: "galletas", d: 2 },
  { a: "Madrid", b: "Barcelona", d: 2 },
  { a: "desierto", b: "selva", d: 2 },
  { a: "bicicleta", b: "patineta", d: 2 },
  { a: "sushi", b: "paella", d: 2 },
  { a: "zapatos", b: "chanclas", d: 2 },
  { a: "libro", b: "periódico", d: 2 },
  { a: "restaurante", b: "cafetería", d: 2 },
  { a: "Navidad", b: "Halloween", d: 2 },
  { a: "lluvia", b: "nieve", d: 2 },
  { a: "manzana", b: "sandía", d: 2 },
  { a: "taxi", b: "autobús", d: 2 },
  { a: "playa", b: "parque", d: 2 },
  { a: "cantante", b: "actor", d: 2 },
  { a: "correr", b: "nadar", d: 2 },
  { a: "gimnasio", b: "yoga", d: 2 },
  { a: "plátano", b: "mango", d: 2 },
  { a: "guacamole", b: "salsa picante", d: 2 },
  { a: "policía", b: "bombero", d: 2 },
  { a: "rosa", b: "girasol", d: 2 },
  { a: "pasta", b: "arroz", d: 2 },
  { a: "refrigerador", b: "horno", d: 2 },
  { a: "mochila", b: "maleta", d: 2 },
  { a: "reloj", b: "collar", d: 2 },
  { a: "lavadora", b: "lavavajillas", d: 2 },
  { a: "médico", b: "veterinario", d: 2 },
  { a: "mamá", b: "abuela", d: 2 },
  { a: "bebé", b: "cachorro", d: 2 },
  { a: "ducha", b: "bañera", d: 2 },
  { a: "ascensor", b: "escaleras", d: 2 },
  { a: "almohada", b: "manta", d: 2 },
  { a: "asado", b: "picnic", d: 2 },
  { a: "cumpleaños", b: "Año Nuevo", d: 2 },
  { a: "Facebook", b: "TikTok", d: 2 },
  { a: "campamento", b: "hotel", d: 2 },
  { a: "Machu Picchu", b: "Chichén Itzá", d: 2 },
  { a: "cartera", b: "bolso", d: 2 },
  { a: "leche", b: "jugo", d: 2 },
  { a: "semáforo", b: "señal de tránsito", d: 2 },
  { a: "profesor", b: "entrenador", d: 2 },
  { a: "churros", b: "donas", d: 2 },
  { a: "piñata", b: "globo", d: 2 },
  { a: "salsa", b: "tango", d: 2 },
  { a: "Messi", b: "Cristiano Ronaldo", d: 2 },
  { a: "mate", b: "chocolate caliente", d: 2 },
  { a: "tortilla", b: "arepa", d: 2 },
  { a: "ceviche", b: "ensalada", d: 2 },
  { a: "elefante", b: "jirafa", d: 2 },
  { a: "tiburón", b: "delfín", d: 2 },
  { a: "león", b: "tigre", d: 2 },
  { a: "caballo", b: "burro", d: 2 },
  { a: "pingüino", b: "pato", d: 2 },
  { a: "abeja", b: "mariposa", d: 2 },
  { a: "tortuga", b: "caracol", d: 2 },
  { a: "Batman", b: "Spider-Man", d: 2 },
  { a: "Shrek", b: "Bob Esponja", d: 2 },
  { a: "Mario", b: "Sonic", d: 2 },
  { a: "Pikachu", b: "Goku", d: 2 },
  { a: "Harry Potter", b: "Frozen", d: 2 },
  { a: "Netflix", b: "YouTube", d: 2 },
  { a: "teléfono", b: "computadora", d: 2 },
  { a: "WhatsApp", b: "correo electrónico", d: 2 },
  { a: "volcán", b: "montaña", d: 2 },
  { a: "río", b: "lago", d: 2 },
  { a: "isla", b: "península", d: 2 },
  { a: "castillo", b: "pirámide", d: 2 },
  { a: "Argentina", b: "México", d: 2 },
  { a: "España", b: "Italia", d: 2 },
  { a: "primavera", b: "otoño", d: 2 },
  { a: "dentista", b: "peluquero", d: 2 },
  { a: "hospital", b: "farmacia", d: 2 },
  { a: "supermercado", b: "mercado", d: 2 },
  { a: "zapatería", b: "panadería", d: 2 },
  { a: "fresa", b: "limón", d: 2 },
  { a: "pan", b: "queso", d: 2 },
  { a: "sopa", b: "sándwich", d: 2 },
  { a: "karaoke", b: "discoteca", d: 2 },
  { a: "ajedrez", b: "dominó", d: 2 },
  { a: "lotería", b: "bingo", d: 2 },
  /* ---------- d:1 — difícil ---------- */
  { a: "fresa", b: "cereza", d: 1 },
  { a: "mediodía", b: "tarde", d: 1 },
  { a: "dentista", b: "oculista", d: 1 },
  { a: "Tierra", b: "Marte", d: 1 },
  { a: "hormiga", b: "cucaracha", d: 1 },
  { a: "latte", b: "capuchino", d: 1 },
  { a: "Marvel", b: "DC", d: 1 },
  { a: "iPhone", b: "Samsung", d: 1 },
  { a: "limón", b: "lima", d: 1 },
  { a: "tomate", b: "pimiento", d: 1 },
  { a: "kétchup", b: "mayonesa", d: 1 },
  { a: "perfume", b: "desodorante", d: 1 },
  { a: "collar", b: "pulsera", d: 1 },
  { a: "anillo", b: "arete", d: 1 },
  { a: "corona", b: "casco", d: 1 },
  { a: "ascensor", b: "escalera mecánica", d: 1 },
  { a: "autobús", b: "tranvía", d: 1 },
  { a: "gemelos", b: "hermanos", d: 1 },
  { a: "tío", b: "primo", d: 1 },
  { a: "mantequilla", b: "margarina", d: 1 },
  { a: "azúcar", b: "miel", d: 1 },
  { a: "sal", b: "pimienta", d: 1 },
  { a: "leche", b: "yogur", d: 1 },
  { a: "Coca-Cola", b: "Pepsi", d: 1 },
  { a: "Nike", b: "Adidas", d: 1 },
  { a: "McDonald's", b: "Burger King", d: 1 },
  { a: "WhatsApp", b: "Telegram", d: 1 },
  { a: "Instagram", b: "TikTok", d: 1 },
  { a: "Netflix", b: "Disney+", d: 1 },
  { a: "PlayStation", b: "Xbox", d: 1 },
  { a: "Chrome", b: "Safari", d: 1 },
  { a: "tenis", b: "pádel", d: 1 },
  { a: "ballet", b: "gimnasia", d: 1 },
  { a: "abogado", b: "juez", d: 1 },
  { a: "chef", b: "panadero", d: 1 },
  { a: "piloto", b: "azafata", d: 1 },
  { a: "cantante", b: "rapero", d: 1 },
  { a: "violín", b: "violonchelo", d: 1 },
  { a: "trompeta", b: "saxofón", d: 1 },
  { a: "salsa", b: "merengue", d: 1 },
  { a: "tango", b: "flamenco", d: 1 },
  { a: "taco", b: "quesadilla", d: 1 },
  { a: "burrito", b: "enchilada", d: 1 },
  { a: "empanada", b: "tamal", d: 1 },
  { a: "churro", b: "buñuelo", d: 1 },
  { a: "paella", b: "arroz con pollo", d: 1 },
  { a: "ceviche", b: "sashimi", d: 1 },
  { a: "mar", b: "océano", d: 1 },
  { a: "lago", b: "laguna", d: 1 },
  { a: "colina", b: "montaña", d: 1 },
  { a: "lluvia", b: "llovizna", d: 1 },
  { a: "niebla", b: "humo", d: 1 },
  { a: "estrella", b: "planeta", d: 1 },
  { a: "cometa", b: "meteorito", d: 1 },
  { a: "rana", b: "sapo", d: 1 },
  { a: "cocodrilo", b: "caimán", d: 1 },
  { a: "mariposa", b: "polilla", d: 1 },
  { a: "abeja", b: "avispa", d: 1 },
  { a: "lobo", b: "coyote", d: 1 },
  { a: "leopardo", b: "guepardo", d: 1 },
  { a: "delfín", b: "ballena", d: 1 },
  { a: "paloma", b: "gaviota", d: 1 },
  { a: "Messi", b: "Maradona", d: 1 },
  { a: "Shakira", b: "Karol G", d: 1 },
  { a: "Bad Bunny", b: "Daddy Yankee", d: 1 },
  { a: "Buenos Aires", b: "Montevideo", d: 1 },
  { a: "martes", b: "jueves", d: 1 },
  { a: "enero", b: "febrero", d: 1 },
  { a: "minuto", b: "segundo", d: 1 },
  { a: "medianoche", b: "madrugada", d: 1 },
  { a: "lápiz", b: "bolígrafo", d: 1 },
  { a: "cuaderno", b: "agenda", d: 1 },
  { a: "sartén", b: "olla", d: 1 },
  { a: "tenedor", b: "cuchara", d: 1 },
  { a: "vaso", b: "taza", d: 1 },
  { a: "bufanda", b: "pañuelo", d: 1 },
  { a: "gorra", b: "sombrero", d: 1 },
  { a: "botas", b: "botines", d: 1 },
  ],
  trivia: [
  { q: "¿En qué país nació el tango?", options: ["Brasil", "Argentina", "Colombia", "Cuba"], correct: 1, cat: "israel" },
  { q: "¿En qué ciudad está la Sagrada Familia de Gaudí?", options: ["Madrid", "Sevilla", "Valencia", "Barcelona"], correct: 3, cat: "israel" },
  { q: "¿Cuál es el país hispanohablante con más habitantes?", options: ["España", "Argentina", "México", "Colombia"], correct: 2, cat: "israel" },
  { q: "¿En qué país está Machu Picchu?", options: ["Bolivia", "Perú", "Ecuador", "Chile"], correct: 1, cat: "israel" },
  { q: "¿Cómo se llama la bebida de yerba que se toma con bombilla?", options: ["Chicha", "Horchata", "Mate", "Atole"], correct: 2, cat: "israel" },
  { q: "¿Qué país tiene forma alargada y estrecha junto a los Andes?", options: ["Chile", "Argentina", "Perú", "Uruguay"], correct: 0, cat: "israel" },
  { q: "¿Dónde nació la tradición de las doce uvas de Nochevieja?", options: ["España", "México", "Argentina", "Cuba"], correct: 0, cat: "israel" },
  { q: "¿Qué animal aparece en la bandera de México?", options: ["Cóndor", "Jaguar", "Águila", "Quetzal"], correct: 2, cat: "israel" },
  { q: "¿En qué país están las Islas Galápagos?", options: ["Perú", "Chile", "Colombia", "Ecuador"], correct: 3, cat: "israel" },
  { q: "¿Qué país celebra el Día de Muertos con calaveras de azúcar?", options: ["Perú", "Chile", "Cuba", "México"], correct: 3, cat: "israel" },
  { q: "¿En qué país está el Salto Ángel, la cascada más alta del mundo?", options: ["Colombia", "Brasil", "Venezuela", "Perú"], correct: 2, cat: "israel" },
  { q: "¿Cuál es la capital de Colombia?", options: ["Medellín", "Bogotá", "Cali", "Cartagena"], correct: 1, cat: "israel" },
  { q: "¿Qué país de Centroamérica no tiene ejército desde 1948?", options: ["Panamá", "Costa Rica", "Honduras", "Guatemala"], correct: 1, cat: "israel" },
  { q: "¿Cuál es la capital de Australia?", options: ["Sídney", "Melbourne", "Canberra", "Perth"], correct: 2, cat: "world" },
  { q: "¿Cuál es el océano más grande del mundo?", options: ["Pacífico", "Atlántico", "Índico", "Ártico"], correct: 0, cat: "world" },
  { q: "¿En qué país están las pirámides de Giza?", options: ["México", "Egipto", "Perú", "Sudán"], correct: 1, cat: "world" },
  { q: "¿Cuál es el río más caudaloso del mundo?", options: ["Nilo", "Amazonas", "Misisipi", "Yangtsé"], correct: 1, cat: "world" },
  { q: "¿Cuál es el país más grande del mundo en superficie?", options: ["Canadá", "China", "Brasil", "Rusia"], correct: 3, cat: "world" },
  { q: "¿Qué país tiene forma de bota?", options: ["Grecia", "Italia", "Portugal", "Turquía"], correct: 1, cat: "world" },
  { q: "¿Cuál es el país más pequeño del mundo?", options: ["Mónaco", "Malta", "Vaticano", "San Marino"], correct: 2, cat: "world" },
  { q: "¿Qué país tiene una hoja de arce en su bandera?", options: ["Suecia", "Noruega", "Nueva Zelanda", "Canadá"], correct: 3, cat: "world" },
  { q: "¿Qué país tiene más islas en el mundo?", options: ["Suecia", "Indonesia", "Filipinas", "Japón"], correct: 0, cat: "world" },
  { q: "¿Qué ciudad es famosa por sus canales y góndolas?", options: ["Ámsterdam", "Brujas", "Estocolmo", "Venecia"], correct: 3, cat: "world" },
  { q: "¿Cuántos corazones tiene un pulpo?", options: ["1", "2", "3", "8"], correct: 2, cat: "science" },
  { q: "¿Cuál es el planeta más grande del sistema solar?", options: ["Júpiter", "Saturno", "Marte", "Neptuno"], correct: 0, cat: "science" },
  { q: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Hígado", "Piel", "Cerebro", "Pulmones"], correct: 1, cat: "science" },
  { q: "¿Cuántos huesos tiene el cuerpo de un adulto?", options: ["150", "106", "206", "306"], correct: 2, cat: "science" },
  { q: "¿De qué elemento está hecho un diamante?", options: ["Hierro", "Oro", "Silicio", "Carbono"], correct: 3, cat: "science" },
  { q: "¿Cuál es el animal terrestre más rápido?", options: ["León", "Guepardo", "Caballo", "Avestruz"], correct: 1, cat: "science" },
  { q: "¿Cuánto tarda la luz del Sol en llegar a la Tierra?", options: ["8 segundos", "8 minutos", "8 horas", "8 días"], correct: 1, cat: "science" },
  { q: "¿Cuál es el hueso más pequeño del cuerpo humano?", options: ["Estribo", "Fémur", "Costilla", "Rótula"], correct: 0, cat: "science" },
  { q: "¿Cuál es el único mamífero que vuela de verdad?", options: ["Ardilla voladora", "Lémur", "Colibrí", "Murciélago"], correct: 3, cat: "science" },
  { q: "¿Qué metal es líquido a temperatura ambiente?", options: ["Mercurio", "Plomo", "Plata", "Estaño"], correct: 0, cat: "science" },
  ],
};
