/** Português 🇧🇷 — conteúdo local para o Brasil (e Portugal) */
import type { LangContent } from "./types";

export const pt: LangContent = {
  decks: {
  animals: {
    cards: [
      "Leão", "Elefante", "Girafa", "Macaco", "Cachorro", "Gato", "Pinguim", "Golfinho", "Tubarão", "Polvo",
      "Canguru", "Coala", "Zebra", "Hipopótamo", "Rinoceronte", "Tigre", "Urso", "Lobo", "Raposa", "Coelho",
      "Tartaruga", "Cobra", "Jacaré", "Aranha", "Abelha", "Borboleta", "Coruja", "Águia", "Papagaio", "Pavão",
      "Cavalo", "Burro", "Vaca", "Ovelha", "Cabra", "Galo", "Pato", "Ganso", "Rato", "Hamster",
      "Capivara", "Tucano", "Arara", "Onça-pintada", "Tamanduá", "Bicho-preguiça", "Boto-cor-de-rosa", "Mico-leão-dourado", "Lobo-guará", "Piranha",
    ],
  },
  celebs: {
    cards: [
      "Anitta", "Ivete Sangalo", "Roberto Carlos", "Pelé", "Neymar", "Ronaldinho Gaúcho", "Marta", "Xuxa", "Silvio Santos", "Faustão",
      "Ayrton Senna", "Santos Dumont", "Gisele Bündchen", "Fernanda Montenegro", "Wagner Moura", "Gilberto Gil", "Caetano Veloso", "Luciano Huck", "Ana Maria Braga", "Tom Jobim",
      "Zico", "Ronaldo Fenômeno", "Gusttavo Lima", "Marília Mendonça", "Whindersson Nunes", "Larissa Manoela", "Chico Buarque", "Renato Aragão (Didi)", "Tiradentes", "Dom Pedro I",
      "Cristiano Ronaldo", "Lionel Messi", "Michael Jackson", "Taylor Swift", "Beyoncé", "Elon Musk",
    ],
  },
  food: {
    cards: [
      "Feijoada", "Pão de queijo", "Brigadeiro", "Coxinha", "Açaí na tigela", "Churrasco", "Pastel de feira", "Tapioca", "Guaraná", "Farofa",
      "Moqueca", "Acarajé", "Pudim de leite", "Beijinho", "Quindim", "Bolo de fubá", "Mandioca frita", "Pão francês", "Misto quente", "Cuscuz",
      "Picanha", "Paçoca", "Goiabada com queijo", "Bolinho de chuva", "Caldo de cana", "Vatapá", "Pizza", "Hambúrguer", "Sushi", "Lasanha",
      "Batata frita", "Sorvete", "Manga", "Abacaxi", "Maracujá", "Jabuticaba", "Caju", "Banana", "Chocolate", "Milho cozido",
    ],
  },
  cartoons: {
    cards: [
      "Bob Esponja", "Patrick Estrela", "Mônica", "Cebolinha", "Cascão", "Magali", "Peppa Pig", "Homer Simpson", "Bart Simpson", "Elsa (Frozen)",
      "Shrek", "Pikachu", "Mario", "Goku", "Galinha Pintadinha", "Mickey Mouse", "Pato Donald", "Pernalonga", "Scooby-Doo", "Tom (Tom e Jerry)",
      "Jerry", "Woody (Toy Story)", "Buzz Lightyear", "Nemo", "Homem-Aranha", "Batman", "Ursinho Pooh", "Minion", "Naruto", "Pica-Pau",
      "Moana", "Simba", "Hulk", "Mulher-Maravilha",
    ],
  },
  },
  impostorPairs: [
  ["pizza", "hambúrguer"], ["gato", "cachorro"], ["praia", "piscina"], ["café", "chá"], ["avião", "ônibus"],
  ["casamento", "festa de 15 anos"], ["futebol", "vôlei"], ["Carnaval", "Réveillon"], ["Rio de Janeiro", "São Paulo"], ["coxinha", "pastel"],
  ["violão", "piano"], ["sol", "lua"], ["sorvete", "picolé"], ["chuveiro", "banheira"], ["médico", "enfermeira"],
  ["escola", "faculdade"], ["mãe", "avó"], ["televisão", "cinema"], ["sofá", "cama"], ["inverno", "outono"],
  ["vinho", "cerveja"], ["bolo", "biscoito"], ["deserto", "floresta"], ["bicicleta", "patinete"], ["feijoada", "churrasco"],
  ["tênis", "chinelo"], ["óculos", "lente de contato"], ["livro", "jornal"], ["restaurante", "padaria"], ["Natal", "Páscoa"],
  ["chuva", "neve"], ["maçã", "pera"], ["chocolate", "brigadeiro"], ["táxi", "metrô"], ["semáforo", "placa de trânsito"],
  ["parque", "shopping"], ["viagem à praia", "viagem à serra"], ["professor", "treinador"], ["bebê", "filhote"], ["leite", "achocolatado"],
  ["Facebook", "Instagram"], ["domingo", "feriado"], ["elevador", "escada"], ["travesseiro", "cobertor"], ["churrasco", "piquenique"],
  ["cantor", "ator"], ["bolo de aniversário", "pudim"], ["corrida", "caminhada"], ["academia", "yoga"], ["banana", "manga"],
  ["pão de queijo", "pão francês"], ["policial", "segurança"], ["creche", "colônia de férias"], ["rosa", "girassol"], ["Amazônia", "Pantanal"],
  ["macarrão", "arroz"], ["geladeira", "ar-condicionado"], ["carteira", "mochila"], ["relógio", "pulseira"], ["guaraná", "coca-cola"],
  ["samba", "forró"], ["Copacabana", "Ipanema"], ["tapioca", "crepe"], ["açaí", "sorvete"], ["Flamengo", "Corinthians"],
  ],
  undercoverPairs: [
  /* ---------- d:2 — normal ---------- */
  { a: "pizza", b: "hambúrguer", d: 2 },
  { a: "gato", b: "cachorro", d: 2 },
  { a: "mar", b: "piscina", d: 2 },
  { a: "café", b: "chá", d: 2 },
  { a: "avião", b: "trem", d: 2 },
  { a: "casamento", b: "festa de 15 anos", d: 2 },
  { a: "coxinha", b: "pastel", d: 2 },
  { a: "futebol", b: "basquete", d: 2 },
  { a: "violão", b: "piano", d: 2 },
  { a: "sol", b: "lua", d: 2 },
  { a: "sorvete", b: "chocolate", d: 2 },
  { a: "escola", b: "faculdade", d: 2 },
  { a: "televisão", b: "cinema", d: 2 },
  { a: "sofá", b: "cama", d: 2 },
  { a: "inverno", b: "verão", d: 2 },
  { a: "vinho", b: "cerveja", d: 2 },
  { a: "bolo", b: "biscoito", d: 2 },
  { a: "Rio de Janeiro", b: "São Paulo", d: 2 },
  { a: "deserto", b: "floresta", d: 2 },
  { a: "bicicleta", b: "patinete", d: 2 },
  { a: "sushi", b: "feijoada", d: 2 },
  { a: "tênis", b: "chinelo", d: 2 },
  { a: "livro", b: "jornal", d: 2 },
  { a: "restaurante", b: "padaria", d: 2 },
  { a: "Carnaval", b: "Natal", d: 2 },
  { a: "chuva", b: "neve", d: 2 },
  { a: "maçã", b: "melancia", d: 2 },
  { a: "táxi", b: "ônibus", d: 2 },
  { a: "praia", b: "parque", d: 2 },
  { a: "cantor", b: "ator", d: 2 },
  { a: "corrida", b: "natação", d: 2 },
  { a: "academia", b: "yoga", d: 2 },
  { a: "banana", b: "manga", d: 2 },
  { a: "policial", b: "bombeiro", d: 2 },
  { a: "creche", b: "colônia de férias", d: 2 },
  { a: "rosa", b: "cacto", d: 2 },
  { a: "Amazônia", b: "Pantanal", d: 2 },
  { a: "macarrão", b: "arroz", d: 2 },
  { a: "geladeira", b: "ar-condicionado", d: 2 },
  { a: "carteira", b: "mala", d: 2 },
  { a: "guarda-chuva", b: "boné", d: 2 },
  { a: "leão", b: "elefante", d: 2 },
  { a: "tubarão", b: "golfinho", d: 2 },
  { a: "papagaio", b: "pombo", d: 2 },
  { a: "abelha", b: "formiga", d: 2 },
  { a: "helicóptero", b: "navio", d: 2 },
  { a: "moto", b: "trator", d: 2 },
  { a: "máquina de lavar", b: "lava-louças", d: 2 },
  { a: "travesseiro", b: "cobertor", d: 2 },
  { a: "churrasco", b: "piquenique", d: 2 },
  { a: "circo", b: "parque de diversões", d: 2 },
  { a: "museu", b: "biblioteca", d: 2 },
  { a: "hospital", b: "salão de beleza", d: 2 },
  { a: "supermercado", b: "feira", d: 2 },
  { a: "torradeira", b: "micro-ondas", d: 2 },
  { a: "pipoca", b: "paçoca", d: 2 },
  { a: "chiclete", b: "pirulito", d: 2 },
  { a: "coca-cola", b: "suco de laranja", d: 2 },
  { a: "leite", b: "achocolatado", d: 2 },
  { a: "ovo", b: "queijo", d: 2 },
  { a: "salada", b: "sopa", d: 2 },
  { a: "bife", b: "almôndega", d: 2 },
  { a: "pão francês", b: "tapioca", d: 2 },
  { a: "mel", b: "geleia", d: 2 },
  { a: "trovão", b: "relâmpago", d: 2 },
  { a: "nuvem", b: "neblina", d: 2 },
  { a: "montanha", b: "caverna", d: 2 },
  { a: "rio", b: "cachoeira", d: 2 },
  { a: "estrela", b: "cometa", d: 2 },
  { a: "nave espacial", b: "submarino", d: 2 },
  { a: "robô", b: "alienígena", d: 2 },
  { a: "mágico", b: "palhaço", d: 2 },
  { a: "pirata", b: "cavaleiro", d: 2 },
  { a: "rei", b: "presidente", d: 2 },
  { a: "piloto", b: "motorista de táxi", d: 2 },
  { a: "espelho", b: "janela", d: 2 },
  { a: "cama de casal", b: "rede", d: 2 },
  { a: "WhatsApp", b: "e-mail", d: 2 },
  { a: "quebra-cabeça", b: "Lego", d: 2 },
  { a: "bola", b: "balão", d: 2 },
  { a: "vela", b: "lanterna", d: 2 },
  { a: "escorregador", b: "balanço", d: 2 },
  { a: "controle remoto", b: "teclado", d: 2 },
  { a: "cozinha", b: "varanda", d: 2 },
  { a: "férias", b: "fim de semana", d: 2 },
  { a: "aniversário", b: "Réveillon", d: 2 },
  { a: "vôlei", b: "tênis", d: 2 },
  { a: "xadrez", b: "Banco Imobiliário", d: 2 },
  { a: "balé", b: "funk", d: 2 },
  { a: "fotógrafo", b: "pintor", d: 2 },
  { a: "cão-guia", b: "cavalo", d: 2 },
  { a: "capivara", b: "tucano", d: 2 },
  { a: "brigadeiro", b: "coxinha", d: 2 },
  { a: "samba", b: "sertanejo", d: 2 },
  { a: "Copacabana", b: "Cristo Redentor", d: 2 },
  { a: "guaraná", b: "água de coco", d: 2 },

  /* ---------- d:1 — difícil (palavras quase iguais) ---------- */
  { a: "mar", b: "lago", d: 1 },
  { a: "cachorro", b: "lobo", d: 1 },
  { a: "gato", b: "tigre", d: 1 },
  { a: "bicicleta", b: "moto", d: 1 },
  { a: "avião", b: "helicóptero", d: 1 },
  { a: "futebol", b: "futsal", d: 1 },
  { a: "violão", b: "guitarra", d: 1 },
  { a: "coxinha", b: "bolinha de queijo", d: 1 },
  { a: "sorvete", b: "picolé", d: 1 },
  { a: "chuveiro", b: "banheira", d: 1 },
  { a: "médico", b: "enfermeiro", d: 1 },
  { a: "professor", b: "palestrante", d: 1 },
  { a: "policial", b: "segurança", d: 1 },
  { a: "maçã", b: "pera", d: 1 },
  { a: "sofá", b: "poltrona", d: 1 },
  { a: "tênis", b: "sandália", d: 1 },
  { a: "camiseta", b: "moletom", d: 1 },
  { a: "outono", b: "primavera", d: 1 },
  { a: "noite", b: "madrugada", d: 1 },
  { a: "sábado", b: "domingo", d: 1 },
  { a: "Natal", b: "Ano Novo", d: 1 },
  { a: "hotel", b: "pousada", d: 1 },
  { a: "sala", b: "quarto", d: 1 },
  { a: "creche", b: "pré-escola", d: 1 },
  { a: "ensino médio", b: "faculdade", d: 1 },
  { a: "celular", b: "tablet", d: 1 },
  { a: "Instagram", b: "TikTok", d: 1 },
  { a: "YouTube", b: "Netflix", d: 1 },
  { a: "xadrez", b: "dama", d: 1 },
  { a: "baralho", b: "dominó", d: 1 },
  { a: "lápis", b: "caneta", d: 1 },
  { a: "caderno", b: "agenda", d: 1 },
  { a: "tesoura", b: "faca", d: 1 },
  { a: "martelo", b: "chave de fenda", d: 1 },
  { a: "garfo", b: "colher", d: 1 },
  { a: "copo", b: "xícara", d: 1 },
  { a: "prato", b: "tigela", d: 1 },
  { a: "ventilador", b: "ar-condicionado", d: 1 },
  { a: "porta", b: "portão", d: 1 },
  { a: "cerca", b: "muro", d: 1 },
  { a: "escada", b: "escada rolante", d: 1 },
  { a: "sacola", b: "caixa", d: 1 },
  { a: "mala", b: "mochila", d: 1 },
  { a: "cobertor", b: "saco de dormir", d: 1 },
  { a: "toalha", b: "roupão", d: 1 },
  { a: "sabonete", b: "xampu", d: 1 },
  { a: "perfume", b: "desodorante", d: 1 },
  { a: "colar", b: "pulseira", d: 1 },
  { a: "anel", b: "brinco", d: 1 },
  { a: "coroa", b: "capacete", d: 1 },
  { a: "ônibus", b: "metrô", d: 1 },
  { a: "limão", b: "lima", d: 1 },
  { a: "tomate", b: "pimentão", d: 1 },
  { a: "ketchup", b: "maionese", d: 1 },
  { a: "morango", b: "cereja", d: 1 },
  { a: "meio-dia", b: "tarde", d: 1 },
  { a: "dentista", b: "oftalmologista", d: 1 },
  { a: "Terra", b: "Marte", d: 1 },
  { a: "formiga", b: "barata", d: 1 },
  { a: "latte", b: "cappuccino", d: 1 },
  { a: "Marvel", b: "DC", d: 1 },
  { a: "iPhone", b: "Samsung", d: 1 },
  { a: "samba", b: "pagode", d: 1 },
  { a: "forró", b: "sertanejo", d: 1 },
  { a: "Flamengo", b: "Fluminense", d: 1 },
  { a: "brigadeiro", b: "beijinho", d: 1 },
  { a: "pastel", b: "empada", d: 1 },
  { a: "onça", b: "leopardo", d: 1 },
  { a: "tucano", b: "arara", d: 1 },
  { a: "açaí", b: "cupuaçu", d: 1 },
  ],
  trivia: [
  /* ---------- local (Brasil) ---------- */
  { q: "Qual é a capital do Brasil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correct: 2, cat: "israel" },
  { q: "Quantas estrelas tem a bandeira do Brasil?", options: ["26", "27", "25", "30"], correct: 1, cat: "israel" },
  { q: "Qual animal aparece na nota de 100 reais?", options: ["Onça-pintada", "Arara", "Mico-leão-dourado", "Garoupa"], correct: 3, cat: "israel" },
  { q: "Qual capital brasileira fica bem em cima da linha do Equador?", options: ["Macapá", "Manaus", "Belém", "Fortaleza"], correct: 0, cat: "israel" },
  { q: "Qual bebida leva cachaça, limão e açúcar?", options: ["Quentão", "Batida", "Caipirinha", "Guaraná"], correct: 2, cat: "israel" },
  { q: "Qual é o maior estado do Brasil em área?", options: ["Pará", "Amazonas", "Mato Grosso", "Minas Gerais"], correct: 1, cat: "israel" },
  { q: "Em que estado fica Fernando de Noronha?", options: ["Bahia", "Ceará", "Rio Grande do Norte", "Pernambuco"], correct: 3, cat: "israel" },
  { q: "Que time de futebol tem o apelido de Timão?", options: ["Corinthians", "Palmeiras", "Flamengo", "Santos"], correct: 0, cat: "israel" },
  { q: "Qual instrumento marca o ritmo da capoeira?", options: ["Pandeiro", "Berimbau", "Cuíca", "Agogô"], correct: 1, cat: "israel" },
  { q: "Com quantos países o Brasil faz fronteira?", options: ["7", "8", "10", "12"], correct: 2, cat: "israel" },
  { q: "Qual cidade é a terra do frevo?", options: ["Salvador", "Belém", "Manaus", "Recife"], correct: 3, cat: "israel" },
  /* ---------- mundo ---------- */
  { q: "Qual é a capital da Austrália?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2, cat: "world" },
  { q: "Qual é a capital do Canadá?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correct: 1, cat: "world" },
  { q: "Em que país fica Machu Picchu?", options: ["Peru", "Bolívia", "Chile", "México"], correct: 0, cat: "world" },
  { q: "Qual país tem mais fusos horários no mundo?", options: ["Rússia", "Estados Unidos", "China", "França"], correct: 3, cat: "world" },
  { q: "Qual é o menor país do mundo?", options: ["Mônaco", "Vaticano", "Malta", "San Marino"], correct: 1, cat: "world" },
  { q: "Qual é o maior deserto quente do mundo?", options: ["Saara", "Atacama", "Gobi", "Kalahari"], correct: 0, cat: "world" },
  { q: "Em que país fica a Torre de Pisa?", options: ["Espanha", "França", "Itália", "Grécia"], correct: 2, cat: "world" },
  { q: "Qual é o rio mais longo da África?", options: ["Congo", "Níger", "Zambeze", "Nilo"], correct: 3, cat: "world" },
  { q: "Em que país o papel foi inventado?", options: ["Egito", "China", "Índia", "Grécia"], correct: 1, cat: "world" },
  { q: "Qual é o maior país da América do Sul depois do Brasil?", options: ["Argentina", "Colômbia", "Peru", "Venezuela"], correct: 0, cat: "world" },
  /* ---------- ciência ---------- */
  { q: "Quantos corações tem um polvo?", options: ["1", "2", "3", "8"], correct: 2, cat: "science" },
  { q: "Qual planeta é conhecido como planeta vermelho?", options: ["Vênus", "Júpiter", "Saturno", "Marte"], correct: 3, cat: "science" },
  { q: "Qual é o maior órgão do corpo humano?", options: ["Pele", "Fígado", "Cérebro", "Pulmão"], correct: 0, cat: "science" },
  { q: "Quantos ossos tem o corpo humano adulto?", options: ["106", "206", "306", "150"], correct: 1, cat: "science" },
  { q: "Qual é o animal terrestre mais rápido do mundo?", options: ["Leão", "Cavalo", "Guepardo", "Avestruz"], correct: 2, cat: "science" },
  { q: "De que elemento é feito o diamante?", options: ["Ferro", "Ouro", "Silício", "Carbono"], correct: 3, cat: "science" },
  { q: "Qual é o maior planeta do Sistema Solar?", options: ["Júpiter", "Saturno", "Netuno", "Urano"], correct: 0, cat: "science" },
  { q: "Qual metal é líquido em temperatura ambiente?", options: ["Alumínio", "Mercúrio", "Chumbo", "Cobre"], correct: 1, cat: "science" },
  { q: "Quantas patas tem uma aranha?", options: ["6", "10", "8", "12"], correct: 2, cat: "science" },
  { q: "Qual é o osso mais longo do corpo humano?", options: ["Úmero", "Tíbia", "Costela", "Fêmur"], correct: 3, cat: "science" },
  { q: "Qual é o maior animal que já existiu?", options: ["Baleia-azul", "Tiranossauro", "Elefante", "Tubarão-branco"], correct: 0, cat: "science" },
  ],
};
